# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7d86b37806ec2f7813fc528045cb0b73166f2dfb5b1b6c40597cf8d14a2423b48243c45d0e3a6424cb55941a03334cb7cad1813cd381295ab6dc9a4cf28e237

test:
  secret_key_base: 2bfb2531febcc72547cc1d176a50a557e3ee13f0f7034a368f71c75c3570f8865483d0664d356fa1220450087793ec8511f010515cf889c64bb4276789b5d280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
